# Generated by Django 4.1.5 on 2023-09-05 09:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('ec550ba2-d1f9-40ef-bd9d-9ddc19f32adc'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='albums/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('4f56a878-357c-408b-81a1-0b150383bf90'), primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(upload_to='designs/%y/%m/%d/')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2023, 9, 5, 12, 7, 43, 661461))),
                ('album', models.ManyToManyField(blank=True, to='designs.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
