# Generated by Django 4.1.5 on 2023-09-05 09:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d1ee7105-f8c6-451c-8065-d767da5dc7e5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 12, 8, 50, 683472)),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('96edc7b0-2aa4-4dc7-88ab-3709ece6d40a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
