# Generated by Django 4.1.5 on 2023-09-05 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0004_alter_album_uuid_alter_design_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('98f03c83-4553-4861-9d82-b23304387e64'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 33, 46, 585580)),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d84f103d-5269-41da-a425-9432ec66f0fb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
