# Generated by Django 4.1.5 on 2023-09-05 11:41

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_album_uuid_alter_design_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4423d196-5453-47d4-aea5-ab788872399b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='img',
            field=models.ImageField(blank=True, upload_to='designs/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 41, 37, 552439)),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c28355f4-d8fe-4241-812a-c37a22301d47'), primary_key=True, serialize=False, unique=True),
        ),
    ]
