# Generated by Django 4.1.5 on 2023-09-05 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0006_alter_album_uuid_alter_design_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95a5ddee-f8dd-4295-a307-739ce2204cc1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 52, 13, 696305)),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('66d72ceb-cf97-4b3c-ab41-ae2e495482be'), primary_key=True, serialize=False, unique=True),
        ),
    ]
