# Generated by Django 4.2.4 on 2023-09-08 15:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_alter_album_uuid_alter_design_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('da06814e-e859-401b-860a-07def0c1e38c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='img',
            field=models.ImageField(upload_to='designs/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 18, 35, 14, 104374)),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ada9da07-e184-4061-9a66-d0390e4b0c31'), primary_key=True, serialize=False, unique=True),
        ),
    ]
